server:
  port: 8888

spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        tags: user.name=${security.user.name}, user.password=${security.user.password}
      host: registry
      port: 8500
    config:
      server:
        git:
          uri: https://github.com/zhangxd1989/spring-boot-cloud
          search-paths: config-repo
          default-label: consul
  rabbitmq:
    host: rabbitmq

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
